### ISSUE TITLE
DEPRECATION WARNING on ansible.utils.unicode.to_str

### ISSUE THREAD

**Issue by fabriziopandini** [fabriziopandini/vagrant-playbook#11]
Running
`$ vagrant-playbook -f cluster-setup.yaml`

We got this message from ansible:
`[DEPRECATION WARNING]: ansible.utils.unicode.to_str is deprecated.  Use ansible.module_utils._text.to_native instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

**Comment by fabriziopandini** [comment]
According to https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst the 2.4 release of ansible targets Target: Mid-September 2017;

**Comment by fabriziopandini** [comment]
`ansible.module_utils._text` warns that `This module_util is currently internal implementation.
    We want to evaluate this code for stability and API suitability before
    making backwards compatibility guarantees.  The API may change between
    releases.  Do not use this unless you are willing to port your module code.` so it is not clear if this is stable or not. trying to reach out someone in the ansible team to get this sorted out

**Comment by fabriziopandini** [comment]
#rabin-io
I fixed this as well with the same approach of #12 (similar to vendoring in golang)
NB This is not yet the complete removal from ansible depencency, but it removes this annoyng message.

Version 0.7.5 is out !
Please let me know if I can close this issue as well

**Comment by rabin-io** [comment]
yep, seems to be resolved.

thanks again.
